services:
  messages-storage:
    image: redis:5.0.7
    ports:
      - 6380:6379

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
